<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/models/spaceship.glb
Author: Silversem (https://sketchfab.com/Silversem)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-2b07b45c32df44fa8a9591c28d5f3487
Title: Spaceship
-->

<script lang="ts">
	import { Group, Material } from 'three';
	import { T, forwardEventHandlers, useTask } from '@threlte/core';
	import { useGltf, useTexture } from '@threlte/extras';
	import Beam from './Beam.svelte';

	export const ref = new Group();

	const gltf = useGltf('models/spaceship.glb');

	// gltf.then((model) => {
	// 	function alphaFix(material: Material) {
	// 		material.transparent = true;
	// 		material.alphaToCoverage = true;
	// 		material.depthTest = true;
	// 		material.depthWrite = true;
	// 	}
	// 	alphaFix(model.materials.spaceship_racer);
	// 	alphaFix(model.materials.cockpit);
	// });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group scale={0.005} rotation={[0, -Math.PI / 2, 0]} position={[0.95, 0, 0]}>
			<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<T.Group position={[-1.02, 1.84, 0.02]}>
					<T.Mesh geometry={gltf.nodes.StopU001_Ship_0.geometry} material={gltf.materials.Ship} />
					<T.Mesh geometry={gltf.nodes.StopU001_Temen_0.geometry} material={gltf.materials.Temen} />
				</T.Group>
				<T.Group position={[-1.02, 1.84, 0.02]}>
					<T.Mesh geometry={gltf.nodes.StopD001_Ship_0.geometry} material={gltf.materials.Ship} />
					<T.Mesh geometry={gltf.nodes.StopD001_Temen_0.geometry} material={gltf.materials.Temen} />
				</T.Group>
				<T.Group position={[-1.02, 0.44, 0.02]}>
					<T.Mesh geometry={gltf.nodes.Vint001_Ship_0.geometry} material={gltf.materials.Ship} />
					<T.Mesh geometry={gltf.nodes.Vint001_Temen_0.geometry} material={gltf.materials.Temen} />
				</T.Group>
				<T.Group position={[1.02, 0.44, 0.02]}>
					<T.Mesh geometry={gltf.nodes.Vint002_Ship_0.geometry} material={gltf.materials.Ship} />
					<T.Mesh geometry={gltf.nodes.Vint002_Temen_0.geometry} material={gltf.materials.Temen} />
				</T.Group>
				<T.Mesh geometry={gltf.nodes.Ship_Ship_0.geometry} material={gltf.materials.Ship} />
				<T.Mesh geometry={gltf.nodes.Ship_Temen_0.geometry} material={gltf.materials.Temen} />
				<T.Mesh
					geometry={gltf.nodes.Gun_Ship_0.geometry}
					material={gltf.materials.Ship}
					position={[0, -0.54, -0.03]}
				/>
				<T.Mesh
					geometry={gltf.nodes.StopU002_Ship_0.geometry}
					material={gltf.materials.Ship}
					position={[1.02, 1.84, 0.02]}
					scale={[-1, 1, 1]}
				/>
				<T.Mesh
					geometry={gltf.nodes.StopD002_Ship_0.geometry}
					material={gltf.materials.Ship}
					position={[1.02, 1.84, 0.02]}
					scale={[-1, 1, 1]}
				/>
			</T.Group>
			<Beam pos={[100, 0, -380]} />
			<Beam pos={[-100, 0, -380]} />
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
